### ISSUE TITLE
Error "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './runs/fit_24/ExtKG__IntKG_lambda:0.000200__SampleRange:50' "

### ISSUE THREAD

**Issue by anikashc** [mysbupt/KERN#1]
I keep on getting this error when running the train.py file

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './runs/fit_24/ExtKG__IntKG_lambda:0.000200__SampleRange:50'

What should I do about it?

**Comment by mysbupt** [comment]
> I keep on getting this error when running the train.py file
> 
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './runs/fit_24/ExtKG__IntKG_lambda:0.000200__SampleRange:50'
> 
> What should I do about it?

**Comment by mysbupt** [comment]
I think this is because the file path formats are different between Linux and Windows. This code should be run on Linux (and we just test it on Ubuntu). If you want to run on Window, you need to make some adataptations, such as the file path format (there may be other stuff to be changed because of different OS).

**Comment by anikashc** [comment]
Thank you for this.
