### ISSUE TITLE
How to draw a trend chart based on reasoning data?

### ISSUE THREAD

**Issue by flysssss** [mysbupt/KERN#3]
What is the meaning of 26x2033, file:   all_pred_geostyle_26.xlsx
There is a little little information, and it can't be seen in the code

**Comment by flysssss** [comment]
It is better to provide the code of the visualization part of the result data!

**Comment by flysssss** [comment]
Is there a recommended engineering implementation in the direction of fashion trend prediction, which can visualize the results end-to-end

**Comment by mysbupt** [comment]
Thanks for the interest to this work. 

To visualize or plot a curve, there are many public libraries or tools such as matplotlib or even excel, which is quite straightforward. So we do not provide such code and just provide the model code.

**Comment by mysbupt** [comment]
The returned variable pred in this line https://github.com/mysbupt/KERN/blob/25323a089294c3b88ac28b3b25301cd567caab21/train.py#L152 is the predicted timeseries, it is just a list and you can plot it using any public visualizer.

**Comment by flysssss** [comment]
Thank you for your quick reply. I want to know the meaning of the data. The npy file has been converted into an xsl file. Now I'm confused about the data in it.

**Comment by flysssss** [comment]
![image](https://user-images.githubusercontent.com/100752067/203764704-49c1b8b9-754a-4ddb-a8ea-966978cce292.png)

**Comment by mysbupt** [comment]
I don't think we have included such np to xsl convert code in our repo. So, I am afraid I cannot interprete your screenshotted data. But if you use the returned variable "pred" in my above reply, it's shape is [batch_size, length_of_prediction], which means each row is one timeseries, and each colomn is one timestamp in the future you want to predict.

**Comment by flysssss** [comment]
![image](https://user-images.githubusercontent.com/100752067/203766300-ac053826-b835-4fb0-ab75-ea60ee6212bb.png)

**Comment by flysssss** [comment]
I found that each row has 26 groups of data and each column has 2024 groups of data. What do they mean?

**Comment by flysssss** [comment]
![image](https://user-images.githubusercontent.com/100752067/203767767-03b02a90-23c3-4537-bff3-41155d7dbb9b.png)

**Comment by flysssss** [comment]
The project code is great. I have run through and reproduced the indicators in the paper. Now I am confused about the results. How to use all_ pred_ geostyle_ 26. npy file, draw the chart in the paper.

**Comment by mysbupt** [comment]
Thanks! Actually we have an updated version of code and refined dataset structures, please refer to this repo: https://github.com/mysbupt/KERN_reproduce ; the dataset in this "KERN_reproduce" is more clear and intuitive. You may read the utility script https://github.com/mysbupt/KERN_reproduce/blob/master/utility.py and can understand the data structure.

**Comment by mysbupt** [comment]
In that repo, the dataset of FIT looks like:
<img width="894" alt="Screenshot 2022-11-24 at 7 19 28 PM" src="https://user-images.githubusercontent.com/8023556/203772056-02952e91-f08b-42f9-8b6a-480ad0adad48.png">
The FIT_data.json is the timeseries data file. It is a json file and the content looks like: 
<img width="447" alt="Screenshot 2022-11-24 at 7 19 13 PM" src="https://user-images.githubusercontent.com/8023556/203772209-34a920e4-9d5b-4689-8694-0ee1b3907c74.png">
The first level key is the group name, the second level key is the fashion element name, the third level is the timeseries, which is a list of list. Each element of the list is [index_of_this_value_in_the_year, fashion_trend_value]. Since every half-month we have one data point, so the range of "index_of_this_value_in_the_year" is within [0, 23]. Hope the explanation of the data format is clear.

**Comment by flysssss** [comment]
Hello, thank you for your detailed answer. I think I understand. Each line represents a fashion element, and its index id is in test_ grp_ ele_ id_ map_ geostyle. Json file. There are 24 and a half months in a year. So the data in each row is the trend value of the predicted fashion elements in this year.

**Comment by flysssss** [comment]
fit_24  represents every half-month we have one data point.   but  geostyle_26,  What does 26 mean？

**Comment by mysbupt** [comment]
FIT_12 and FIT_24 mean the forecasting length (horizon) are 12 (half year) and 24 (one year), respectively. Geostyle_26 means the forecating length is half year (since for geostyle, it has one datapoint for every week, so there are about 53 data points (weeks) per year. ) You can config the forecasting length through the entry "output_len" in the config file: https://github.com/mysbupt/KERN_reproduce/blob/47f39eb2ee7282cb8ece2e45588a0cdcf7a243b3/config.yaml#L108

**Comment by flysssss** [comment]
Thank you very much for your detailed answers. Good luck！
